twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: '@FOSCKEditor/Form/ckeditor_widget.html.twig'
 
  globals:
      idWebsite: '@App\Repository\Identit√©WebsiteRepository'

when@test:
    twig:
        strict_variables: true